# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "**" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
          # TODO: windows needs more work in the code
          # - windows
        arch:
          - amd64
          - arm64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Prepare
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        go install golang.org/x/tools/cmd/stringer@latest

    - name: Build
      run: |
        case $os in
          macos) export GOOS=darwin ;;
          ubuntu) export GOOS=linux ;;
          *)
            echo "Unsupported OS: $os" >/dev/stderr
            exit 1
            ;;
        esac

        go clean
        make build
        make test
      env:
        os: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: "0"

    - uses: actions/upload-artifact@v4
      with:
        name: nukictl
        path: nukictl*
