# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "**" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        cfg:
          - GOOS: macos
            GOARCH: amd64
            runner: macos-15-intel
          - GOOS: macos
            GOARCH: arm64
            runner: macos-latest
          - GOOS: linux
            GOARCH: amd64
            runner: ubuntu-latest
          - GOOS: linux
            GOARCH: arm64
            runner: ubuntu-24.04-arm
          # TODO: windows needs more work in the code
          # - windows
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Prepare
      run: |
        export PATH=$(go env GOPATH)/bin:$PATH
        go install golang.org/x/tools/cmd/stringer@latest

    - name: Build
      run: |
        go clean
        make build
        make test
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: "0"

    - uses: actions/upload-artifact@v4
      with:
        name: nukictl
        path: nukictl*
