# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["**"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.cfg.runner }}
    strategy:
      matrix:
        cfg:
          - runner: macos-15-intel
            bin_suffix: "darwin-amd64"
          - runner: macos-latest
            bin_suffix: "darwin-arm64"
          - runner: ubuntu-latest
            bin_suffix: "linux-amd64"
          - runner: ubuntu-24.04-arm
            bin_suffix: "linux-arm64"
          # TODO: windows needs more work in the code
          # - windows
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Prepare
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go install golang.org/x/tools/cmd/stringer@latest

      - name: Build
        run: |
          go clean
          make build
          make test
        env:
          BIN_SUFFIX: "-${{ matrix.cfg.bin_suffix }}"

      - uses: actions/upload-artifact@v4
        with:
          name: nukictl-${{ matrix.cfg.bin_suffix }}
          path: nukictl*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: List files
        run: tree
      - name: Create Release
        uses: softprops/action-gh-release@v2
        # if: github.ref_type == 'tag'
        with:
          files: ./artifacts/**/*
          draft: true
          generate_release_notes: true
          make_latest: true
